### ISSUE TITLE
Add `<meta>` tag for `https://mozilla.github.io` Origin-Trial token

### ISSUE THREAD

**Issue by cvan** [mozilla/aframe-xr#10]
Without needing a user to enable the flags for Cardboard or Daydream modes, I would recommend enrolling in the WebVR Origin Trial for Chrome for Android.

Sign up here: https://docs.google.com/forms/d/1OTvEk-VfavyKkMxef0Tvs0RFycl9NNu1vdg3FrqJhX8/viewform?edit_requested=true

**Comment by blairmacintyre** [comment]
Added a trial token to examples/xr/basic/index.html.
