### ISSUE TITLE
VR view on xr/basic example renders incorrectly on iOS mobile

### ISSUE THREAD

**Issue by afantasy** [mozilla/aframe-xr#20]
The scene renders but when VR mode is activated, the scene renders incorrectly. I see strobing white lines when changing the view. On iPhone 6 and 7.

**Comment by blairmacintyre** [comment]
I'm not sure that we've ever tested VR mode on iOS.  In Safari?  The WebXR Viewer?

**Comment by afantasy** [comment]
Looks like I'm getting the same issue on mobile Safari/Firefox/Chrome. iPhone6/iOS 11.4.

Just tried the WebXR Viewer and xr/basic activated VR mode!

**Comment by blairmacintyre** [comment]
If you can see a solution, I’d be happy to accept a PR.  On mobile, we never aimed at supporting anything other than the viewer and googles AR apps

**Comment by afantasy** [comment]
Ah, I see now that standard mobile browsers aren't on supported list at all.

I'm a dev novice, so I don't have any solutions for you. Will have to revisit this one. Thanks for the responses!
