### ISSUE TITLE
Warning component for non supported browser

### ISSUE THREAD

**Issue by Utopiah** [mozilla/aframe-xr#5]
Assuming that this there will still be a transition period for main browsers to include the WebXR API proper and that no polyfill will be sufficient (unlike for WebVR and A-frame) having a warning message to suggest XR Viewer, WebARonARKit or WebARonARCore would be useful.

More projects relying aframe-xr at such an early stage will most likely always have to educate and explain those steps to the users (arguably testers at this point), having a shared component for this would be useful to most.

**Comment by blairmacintyre** [comment]
How would you imagine this working?  Pop up a DOM element automatically, or provide a convenience function for programmers to opt into?

**Comment by Utopiah** [comment]
Yes pop up DOM element with id/class to easily customize. Registering callbacks could be nice but since at this point everybody will display the same information (namely if you have iOS link to XR Viewer in the app store, if you have Android, WebARonARCore) probably overkill.

**Comment by Utopiah** [comment]
Related solution https://github.com/google-ar/three.ar.js/blob/master/src/ARUtils.js#L192

**Comment by machenmusik** [comment]
You mean when using aframe-xr and trying to enter AR mode?  I thought the idea was to allow the same scene to be used for VR, AR and 2D/magic window...

**Comment by Utopiah** [comment]
@machenmusik yes but some content only makes sense in some mode, e.g. if one is measuring space in AR then have a demo showcase in a symbolic 3D environment (as shown with `ARUtils.js`) would be a good step but still suggest to the user to then use a browser that fully supports the required AR features to have the full experience.

**Comment by blairmacintyre** [comment]
@Utopiah but, if it's mode specific, that should be up to the app to deal with, not the underlying library, shouldn't it?  The platform (webxr->three->aframe) should help the dev see what capabilities (ar, vr) are available, and they can react accordingly.

**Comment by machenmusik** [comment]
In the same way that there is a template for "place your device into your Cardboard" it may be useful to have stock materials and apps can decide whether and how to present?

**Comment by blairmacintyre** [comment]
I suppose.  I'm open to someone submitting a PR utility function that displays a box with info and links, when called by the programmer.
