### ISSUE TITLE
There is no ROADMAP.md laying down plans for future releases

### ISSUE THREAD

**Issue by Utopiah** [mozilla/aframe-xr#6]
Even though https://github.com/aframevr/aframe/blob/master/ROADMAP.md wasn't always realistic (cf 0.8 release scheduled for 3 months ago) it still gave a vision to the community at large. Having an equivalent for aframe-xr would give a good sense of where the project is going and eventually when upcoming features or support might get released.

**Comment by blairmacintyre** [comment]
I don't think we want to have such a file:  the project is temporary, with the intent being to get everything merged into aframe itself when three.js and aframe.js finally transition to webxr instead of webvr.
